# Config file for automatic testing at travis-ci.org
language: python

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get install -qq python-numpy python-gevent

python:
#  - "3.3"
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: python setup.py develop

# command to run tests, e.g. python setup.py test
script: make test

notifications:
  slack: actionagile:5Ezu3RW7D4GE8AyYUZBYnUKv
